/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.QLNhanVien;

import DTO.ChucVu;
import DTO.NhanVien;
import EXTENDED.Caution;
import EXTENDED.MyComboBox;
import EXTENDED.Transform;
import static GUI.QLNhanVien.jdlThemNhanVien.checkchucvu;
import GUI.DanhMuc.jdlChucVu;
import static GUI.QLNhanVien.pnlNhanVien.loadnhanvien;
import static GUI.QLNhanVien.pnlNhanVien.manhanvien;
import GUI.HomeScreen;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Admin
 */
public class jdlSuaNhanVien extends javax.swing.JDialog {

    /**
     * Creates new form jdlThemDoDung
     */
    public byte[] photo;

    public jdlSuaNhanVien(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    jdlSuaNhanVien() {
        initComponents();
    }

    private void LoadWhenOpen() {
        ArrayList<NhanVien> arrdd = BLL.BLLNhanVien.GetAllNhanVienbyMa(manhanvien);
        for (NhanVien nv : arrdd) {
            txttennv.setText(nv.getTenNhanvien());
            txtsdt.setText((nv.getSoDienThoai()));
            txtemail.setText((nv.getEmail()));
            if (nv.isGioiTinh()) {
                cbnam.setSelected(true);
                cbnu.setSelected(false);
            } else {
                cbnam.setSelected(false);
                cbnu.setSelected(true);
            }
            if (nv.isTinhTrang()) {
                cbyes.setSelected(true);
                cbno.setSelected(false);
            } else {
                cbyes.setSelected(false);
                cbno.setSelected(true);
            }

            photo = nv.getHinhAnh();
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(photo).getImage().
                    getScaledInstance(lbimage.getWidth(), lbimage.getHeight(), Image.SCALE_DEFAULT));
            lbimage.setIcon(imageIcon);
            txtluong.setText(Transform.SoString(nv.getLuong()));
            txttendangnhap.setText(nv.getTenDangNhap());
            txtmatkhau.setText(nv.getMatKhau());
            datengaysinh.setDate(nv.getNgaySinh());
            txtdiachi.setText(nv.getDiaChi());
        }
        BLL.BLLKhac.LoadCBBKhiMo(cbchucvu, BLL.BLLKhac.loadTenChucVu(arrdd.get(0).getChucVu()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txttennv = new javax.swing.JTextField();
        btnluu = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtsdt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnhinhanh = new javax.swing.JButton();
        lbimage = new javax.swing.JLabel();
        datengaysinh = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbchucvu = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtdiachi = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtmatkhau = new javax.swing.JTextField();
        txtluong = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txttendangnhap = new javax.swing.JTextField();
        cbnam = new javax.swing.JCheckBox();
        cbnu = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        cbyes = new javax.swing.JCheckBox();
        cbno = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Giới tính");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("CẬP NHẬT");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Tên  ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("Ngày sinh");

        txttennv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttennvKeyReleased(evt);
            }
        });

        btnluu.setBackground(new java.awt.Color(27, 188, 155));
        btnluu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnluu.setForeground(new java.awt.Color(255, 255, 255));
        btnluu.setText("Lưu");
        btnluu.setBorderPainted(false);
        btnluu.setFocusPainted(false);
        btnluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluuActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Hủy bỏ");
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtsdt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsdtKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setText("Số điện thoại");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setText("Hình ảnh");

        btnhinhanh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/uploadimg.png"))); // NOI18N
        btnhinhanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhinhanhActionPerformed(evt);
            }
        });

        lbimage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        datengaysinh.setDateFormatString("dd-MM-yyyy");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setText("Email");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setText("Chức vụ");

        cbchucvu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setText("Địa chỉ");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel16.setText("Mật khẩu");

        txtluong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtluongKeyReleased(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel17.setText("Lương");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel18.setText("Tên đăng nhập");

        buttonGroup1.add(cbnam);
        cbnam.setText("Nam");

        buttonGroup1.add(cbnu);
        cbnu.setText("Nữ");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Tình trạng");

        buttonGroup2.add(cbyes);
        cbyes.setText("Còn làm");

        buttonGroup2.add(cbno);
        cbno.setText("Đã nghỉ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtsdt)
                                                .addComponent(datengaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txttennv)
                                                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbnam)
                                                .addGap(18, 18, 18)
                                                .addComponent(cbnu))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbyes)
                                                .addGap(18, 18, 18)
                                                .addComponent(cbno)))
                                        .addGap(168, 168, 168)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbchucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton1))
                                            .addComponent(txtluong, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18)
                                            .addComponent(txttendangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnhinhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(39, 39, 39)
                                                .addComponent(lbimage, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel11)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btnluu, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(txtmatkhau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(btnhinhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttennv, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(datengaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lbimage, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbchucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbnam)
                            .addComponent(cbnu))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtluong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttendangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbyes)
                    .addComponent(cbno)
                    .addComponent(btnluu)
                    .addComponent(jButton2))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluuActionPerformed
        if (txttennv.getText().equals("")) {
            Caution.ThongBaoDonGian("Thông báo", "Tên không được để trống!");
        } else if (datengaysinh.getDate() == null) {
            Caution.ThongBaoDonGian("Thông báo", "Ngày sinh không được để trống!");
        } else if (!cbnam.isSelected() && !cbnu.isSelected()) {
            Caution.ThongBaoDonGian("Thông báo", "Vui lòng chọn giới tính!");
        } else if (txtsdt.getText().equals("")) {
            Caution.ThongBaoDonGian("Thông báo", "Số điện thoại không được để trống!");
        } else if (txtemail.getText().equals("")) {
            Caution.ThongBaoDonGian("Thông báo", "Email không được để trống!");
        } else if (txtdiachi.getText().equals("")) {
            Caution.ThongBaoDonGian("Thông báo", "Địa chỉ không được để trống!");
        } else if (txtluong.getText().equals("")) {
            Caution.ThongBaoDonGian("Thông báo", "Lương không được để trống!");
        } else if (txttendangnhap.getText().equals("")) {
            Caution.ThongBaoDonGian("Thông báo", "Tên đăng nhập không được để trống!");
        } else if (txtmatkhau.getText().equals("")) {
            Caution.ThongBaoDonGian("Thông báo", "Mật khẩu không được để trống!");
        } else if (photo == null) {
            Caution.ThongBaoDonGian("Thông báo", "Vui lòng chọn hình ảnh!");
        } else if (txtsdt.getText().length() != 10) {
            Caution.ThongBaoDonGian("Thông báo", "Số điện thoại chỉ được 10 số!");
        } else {
            String tennv = txttennv.getText();
            String sdt = txtsdt.getText();
            String email = txtemail.getText();
            String diachi = txtdiachi.getText();
            Double luong = Transform.SoDouble(txtluong.getText());
            String tendn = txttendangnhap.getText();
            String mk = txtmatkhau.getText();
            byte[] img = photo;
            boolean tinhtrang = cbyes.isSelected() ? true : false;
            boolean gioitinh = cbnam.isSelected() ? true : false;
            Date ngaysinh = datengaysinh.getDate();
            Date date = new Date();
            SimpleDateFormat sim = new SimpleDateFormat("yyyy");
            int namsinh = Integer.parseInt(sim.format(ngaysinh));
            int namhientai = Integer.parseInt(sim.format(date));
            if ((namhientai - namsinh < 16)) {
                Caution.ThongBaoDonGian("Thông báo", "Nhân viên " + tennv + " chưa đủ 16 tuổi");
            } else {
                MyComboBox cBB = (MyComboBox) cbchucvu.getSelectedItem();
                int chucvu = cBB.MaInt();

                ArrayList<NhanVien> arr = BLL.BLLNhanVien.GetAllNhanVienbyMa(manhanvien);
                for (NhanVien nv : arr) {
                    if (nv.getMaNhanVien() == (manhanvien) && nv.getSoDienThoai().equals(sdt) && nv.getEmail().equals(email) && nv.getTenDangNhap().equals(tendn)) {
                        NhanVien nvv = new NhanVien(tennv, ngaysinh, chucvu, sdt, email, diachi, gioitinh, luong, tendn, mk, img, tinhtrang);
                        BLL.BLLNhanVien.update(nvv, manhanvien, email);
                        loadnhanvien();
                    } else if (!nv.getSoDienThoai().equals(sdt)) {
                        NhanVien nvv = new NhanVien(tennv, ngaysinh, chucvu, sdt, email, diachi, gioitinh, luong, tendn, mk, img, tinhtrang);
                        BLL.BLLNhanVien.updatechecksdt(nvv, manhanvien, email);
                        loadnhanvien();
                    } else if (!nv.getEmail().equals(email)) {
                        NhanVien nvv = new NhanVien(tennv, ngaysinh, chucvu, sdt, email, diachi, gioitinh, luong, tendn, mk, img, tinhtrang);
                        BLL.BLLNhanVien.updatecheckemail(nvv, manhanvien, email);
                        loadnhanvien();
                    } else if (!nv.getTenDangNhap().equals(tendn)) {
                        NhanVien nvv = new NhanVien(tennv, ngaysinh, chucvu, sdt, email, diachi, gioitinh, luong, tendn, mk, img, tinhtrang);
                        BLL.BLLNhanVien.updatechecktendn(nvv, manhanvien, email);
                        loadnhanvien();
                    }else{
                        NhanVien nvv = new NhanVien(tennv, ngaysinh, chucvu, sdt, email, diachi, gioitinh, luong, tendn, mk, img, tinhtrang);
                        BLL.BLLNhanVien.updatecheck(nvv, manhanvien, email);
                        loadnhanvien();
                    }
                }

            }
        }
    }//GEN-LAST:event_btnluuActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnhinhanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhinhanhActionPerformed
        try {
            JFileChooser fileChooser = new JFileChooser();
            int trangthai = fileChooser.showOpenDialog(null);
            if (trangthai == JFileChooser.APPROVE_OPTION) {
                File file = fileChooser.getSelectedFile();
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(file.toString()).getImage().getScaledInstance(
                        lbimage.getWidth(), lbimage.getHeight(), Image.SCALE_DEFAULT)
                );
                lbimage.setIcon(imageIcon);
                FileInputStream fis = new FileInputStream(file);
                ByteArrayOutputStream bos = new ByteArrayOutputStream();
                byte[] buf = new byte[1024];
                for (int readnum; (readnum = fis.read(buf)) != -1;) {
                    bos.write(buf, 0, readnum);
                }
                photo = bos.toByteArray();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnhinhanhActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ArrayList<ChucVu> arrdv = BLL.BLLKhac.GetAllChucVu();
        BLL.BLLKhac.LoadComboboxChucVu(arrdv, cbchucvu);

        LoadWhenOpen();
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        checkchucvu = false;
        jdlChucVu cv = new jdlChucVu(new HomeScreen(), true);
        cv.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txttennvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttennvKeyReleased
        String ten = txttennv.getText();
        for (int i = 0; i < ten.length(); i++) {
            if (Character.isDigit(ten.charAt(i))) {
                txttennv.setText("");
            }
        }
    }//GEN-LAST:event_txttennvKeyReleased

    private void txtsdtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsdtKeyReleased
        String ten = txtsdt.getText();
        try {
            Double.parseDouble(ten);

        } catch (Exception e) {
            txtsdt.setText("0");
        }
    }//GEN-LAST:event_txtsdtKeyReleased

    private void txtluongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtluongKeyReleased
        String luong = txtluong.getText();
        double tienGB = Transform.SoDouble(luong);
        txtluong.setText(Transform.SoString(tienGB));
    }//GEN-LAST:event_txtluongKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdlSuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdlSuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdlSuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdlSuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdlSuaNhanVien dialog = new jdlSuaNhanVien(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhinhanh;
    private javax.swing.JButton btnluu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbchucvu;
    private javax.swing.JCheckBox cbnam;
    private javax.swing.JCheckBox cbno;
    private javax.swing.JCheckBox cbnu;
    private javax.swing.JCheckBox cbyes;
    private com.toedter.calendar.JDateChooser datengaysinh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbimage;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtluong;
    private javax.swing.JTextField txtmatkhau;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txttendangnhap;
    private javax.swing.JTextField txttennv;
    // End of variables declaration//GEN-END:variables
}
