/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.QLNhanVien;

import DTO.NhanVien;
import GUI.HomeScreen;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.util.ArrayList;

/**
 *
 * @author ADMIN
 */
public class pnlNhanVien extends javax.swing.JPanel {

    /**
     * Creates new form NhanVien
     */
    public static int manhanvien = 0;
    public static String chucvunv;

    public pnlNhanVien() {
        initComponents();
        setBackground(Color.white);
        loadnhanvien();
        tbnhanvien.setDefaultEditor(Object.class, null);
    }

    public static void loadnhanvien() {
        ArrayList<NhanVien> arrdv = BLL.BLLNhanVien.GetAllNhanVien();
        new BLL.BLLNhanVien().DoVaoTableNhanVien(arrdv, tbnhanvien);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnltextfield = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txttimnhanvien = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cbno = new javax.swing.JCheckBox();
        cbyes = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        pnlkhach = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbnhanvien = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1456, 785));

        pnltextfield.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setText("Tìm kiếm");

        txttimnhanvien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txttimnhanvien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttimnhanvienKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttimnhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txttimnhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        pnltextfield.add(jPanel1);

        buttonGroup1.add(cbno);
        cbno.setText("Đã nghỉ");
        cbno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnoActionPerformed(evt);
            }
        });

        buttonGroup1.add(cbyes);
        cbyes.setText("Đang làm");
        cbyes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbyesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbyes)
                .addGap(18, 18, 18)
                .addComponent(cbno)
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbno)
                    .addComponent(cbyes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnltextfield.add(jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        pnltextfield.add(jPanel4);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        pnltextfield.add(jPanel11);

        tbnhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Tên", "Số điện thoại", "Loại khách hàng"
            }
        ));
        tbnhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbnhanvienMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbnhanvien);

        javax.swing.GroupLayout pnlkhachLayout = new javax.swing.GroupLayout(pnlkhach);
        pnlkhach.setLayout(pnlkhachLayout);
        pnlkhachLayout.setHorizontalGroup(
            pnlkhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnlkhachLayout.setVerticalGroup(
            pnlkhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlkhachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnltextfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlkhach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnltextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlkhach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbnhanvienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbnhanvienMousePressed
        int vitri = tbnhanvien.getSelectedRow();
        manhanvien = Integer.parseInt(tbnhanvien.getValueAt(vitri, 1).toString());
        chucvunv = (tbnhanvien.getValueAt(vitri, 5).toString());
        if (evt.getButton() == MouseEvent.BUTTON1) {
            int indexColumn = tbnhanvien.getSelectedColumn();
            manhanvien = Integer.parseInt(tbnhanvien.getValueAt(vitri, 1).toString());
            chucvunv = (tbnhanvien.getValueAt(vitri, 5).toString());
            if (indexColumn == 12) {
                jdlSuaNhanVien jdl = new jdlSuaNhanVien(new HomeScreen(), true);
                jdl.setVisible(true);
            }

        }
    }//GEN-LAST:event_tbnhanvienMousePressed

    private void txttimnhanvienKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimnhanvienKeyReleased
        String ten = txttimnhanvien.getText();
        ArrayList<NhanVien> arrdv = BLL.BLLNhanVien.FindNhanVienByName(ten, ten);
        new BLL.BLLNhanVien().DoVaoTableNhanVien(arrdv, tbnhanvien);
    }//GEN-LAST:event_txttimnhanvienKeyReleased

    private void cbyesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbyesActionPerformed
        ArrayList<NhanVien> arrdv = BLL.BLLNhanVien.GetAllNhanVienByTinhTrang(cbyes.isSelected());
        new BLL.BLLNhanVien().DoVaoTableNhanVien(arrdv, tbnhanvien);
    }//GEN-LAST:event_cbyesActionPerformed

    private void cbnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnoActionPerformed
        ArrayList<NhanVien> arrdv = BLL.BLLNhanVien.GetAllNhanVienByTinhTrang(cbyes.isSelected());
        new BLL.BLLNhanVien().DoVaoTableNhanVien(arrdv, tbnhanvien);
    }//GEN-LAST:event_cbnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbno;
    private javax.swing.JCheckBox cbyes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlkhach;
    private javax.swing.JPanel pnltextfield;
    public static javax.swing.JTable tbnhanvien;
    private javax.swing.JTextField txttimnhanvien;
    // End of variables declaration//GEN-END:variables
}
