/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Chi;

import BLL.BLLNhanVien;
import BLL.BLLPhieuChi;
import static BLL.BLLPhieuChi.LayTinhTrangPhieuChibyMa;
import DTO.ChiTietPhieuChi;
import DTO.PhieuChi;
import EXTENDED.Caution;
import GUI.HomeScreen;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Admin
 */
public class pnlChi extends javax.swing.JPanel {

    /**
     * Creates new form pnlThu
     */
    public static int MaPhieuChi;

    public pnlChi() {
        initComponents();
        LoadTableChiTietByMa();
        LoadTablePhieuChi();
        setBackground(Color.white);
        DemPhieuChi();
    }

    public static void LoadTableChiTietByMa() {
        ArrayList<ChiTietPhieuChi> arr = BLL.BLLPhieuChi.GetAllCTPCbyMa(MaPhieuChi);
        BLL.BLLPhieuChi.DoVaoTable(arr, tbchitiet);
    }

    public static void LoadTablePhieuChi() {
        ArrayList<PhieuChi> arr = BLL.BLLPhieuChi.GetAllPC();
        new BLLPhieuChi().DoVaoTablePhieuChi(arr, tbphieuthu);
    }

    public static void DemPhieuChi() {
        boolean tinhtrang = false;
        int dem = BLLPhieuChi.DemPhieuChi(tinhtrang);
        if (dem < 1) {
            btnxong.setEnabled(false);
            btnnhapexcel.setEnabled(false);
            btntaophieu.setEnabled(true);
        } else if (dem == 1) {
            btntaophieu.setEnabled(false);
            btnxong.setEnabled(true);
            btnnhapexcel.setEnabled(true);
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        pnltable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbphieuthu = new javax.swing.JTable();
        pnlbutton = new javax.swing.JPanel();
        btntaophieu = new javax.swing.JButton();
        btnnhapexcel = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnxong = new javax.swing.JButton();
        pnltimkiemcon = new javax.swing.JPanel();
        txttimkiem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbchitiet = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        tbphieuthu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbphieuthu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbphieuthuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbphieuthuMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbphieuthu);

        javax.swing.GroupLayout pnltableLayout = new javax.swing.GroupLayout(pnltable);
        pnltable.setLayout(pnltableLayout);
        pnltableLayout.setHorizontalGroup(
            pnltableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
            .addGroup(pnltableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE))
        );
        pnltableLayout.setVerticalGroup(
            pnltableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
            .addGroup(pnltableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnltableLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addGap(1, 1, 1)))
        );

        pnlbutton.setLayout(new java.awt.GridLayout(1, 0, 3, 0));

        btntaophieu.setBackground(new java.awt.Color(27, 188, 155));
        btntaophieu.setText("Tạo phiếu");
        btntaophieu.setBorderPainted(false);
        btntaophieu.setFocusPainted(false);
        btntaophieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntaophieuActionPerformed(evt);
            }
        });
        pnlbutton.add(btntaophieu);

        btnnhapexcel.setText("Nhập Excel");
        pnlbutton.add(btnnhapexcel);

        jButton3.setText("Xuất Excel");
        pnlbutton.add(jButton3);

        btnxong.setText("Xong");
        btnxong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxongActionPerformed(evt);
            }
        });
        pnlbutton.add(btnxong);

        txttimkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttimkiemKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Tìm kiếm ");

        javax.swing.GroupLayout pnltimkiemconLayout = new javax.swing.GroupLayout(pnltimkiemcon);
        pnltimkiemcon.setLayout(pnltimkiemconLayout);
        pnltimkiemconLayout.setHorizontalGroup(
            pnltimkiemconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnltimkiemconLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnltimkiemconLayout.setVerticalGroup(
            pnltimkiemconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnltimkiemconLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(pnltimkiemconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnltable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnltimkiemcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(pnltimkiemcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(pnltable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(pnlbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        add(jPanel2);

        tbchitiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbchitiet);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void tbphieuthuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbphieuthuMouseClicked

    }//GEN-LAST:event_tbphieuthuMouseClicked

    private void txttimkiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimkiemKeyReleased
        String input = txttimkiem.getText();
        ArrayList<PhieuChi> arrdv = BLL.BLLPhieuChi.FindPhieuChi(input, input);
        new BLLPhieuChi().DoVaoTablePhieuChi(arrdv, tbphieuthu);
    }//GEN-LAST:event_txttimkiemKeyReleased

    private void btntaophieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntaophieuActionPerformed
        JTextField ten = new JTextField();
        switch (JOptionPane.showConfirmDialog(null, ten, "Nhập tên: ", JOptionPane.YES_NO_OPTION)) {
            case JOptionPane.YES_NO_OPTION:
                int nguoitao = BLLNhanVien.GetAccountNhanVien().getMaNhanVien();
                double tongtien = 0;
                boolean tinhtrang = false;
                PhieuChi pn = new PhieuChi(ten.getText(), nguoitao, tongtien, tinhtrang);
                BLL.BLLPhieuChi.TaoPhieuChi(pn);
                DemPhieuChi();
                LoadTablePhieuChi();
                break;
            case JOptionPane.NO_OPTION:
                break;
        }
    }//GEN-LAST:event_btntaophieuActionPerformed

    private void btnxongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxongActionPerformed
        int MaPhieuThu = BLL.BLLPhieuChi.LayMaPhieuChi();
        double tongtien = BLL.BLLPhieuChi.LayTongTien(MaPhieuThu);
        boolean tinhtrang = true;
        BLLPhieuChi.UpdateTinhTranggPhieuChi(tongtien, tinhtrang, MaPhieuThu);
        Caution.ThongBaoDonGian("Thông báo", "Thành công");
        LoadTablePhieuChi();
        DemPhieuChi();
    }//GEN-LAST:event_btnxongActionPerformed

    private void tbphieuthuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbphieuthuMousePressed
        int index = tbphieuthu.getSelectedRow();
        MaPhieuChi = Integer.parseInt(tbphieuthu.getValueAt(index, 1).toString());
        LoadTableChiTietByMa();
        int indexColumn = tbphieuthu.getSelectedColumn();
        if (!LayTinhTrangPhieuChibyMa(MaPhieuChi)) {
            if (evt.getButton() == MouseEvent.BUTTON1 && indexColumn == 7) {
                jdlThemChiTietPhieuChi jdl = new jdlThemChiTietPhieuChi(new HomeScreen(), true);
                jdl.setVisible(true);
            }
        }


    }//GEN-LAST:event_tbphieuthuMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnnhapexcel;
    public static javax.swing.JButton btntaophieu;
    public static javax.swing.JButton btnxong;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlbutton;
    private javax.swing.JPanel pnltable;
    private javax.swing.JPanel pnltimkiemcon;
    public static javax.swing.JTable tbchitiet;
    public static javax.swing.JTable tbphieuthu;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
}
