/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BLL.BLLBan;
import BLL.BLLDatBan;
import BLL.BLLHoaDon;
import BLL.BLLKhac;
import BLL.BLLOrder;
import DTO.Ban;
import DTO.HoaDon;
import DTO.KhuVuc;
import DTO.LoaiBan;
import EXTENDED.Caution;
import EXTENDED.MyComboBox;
import EXTENDED.handleTime;
import static GUI.ChuyenBan.loadCBBLoaiaBanOKs;
import static GUI.Order.loadCBBLoaiaBanOK;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.SwingUtilities;

/**
 *
 * @author dell 7559
 */
public class DatBan extends javax.swing.JPanel {

    /**
     * Creates new form ChuyenBan
     */
    public DatBan() {
        initComponents();
        loadCBBKhuVuc();
        loadCBBLoaiBan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jSpinField1 = new com.toedter.components.JSpinField();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnDatBan = new javax.swing.JButton();
        btnXong = new javax.swing.JButton();
        btnHuyDat = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        txtNgay = new com.toedter.calendar.JDateChooser();
        txtTenKhach = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jpnBanDaDat = new javax.swing.JPanel();
        CBBKhuVucBanDaDat = new javax.swing.JComboBox<>();
        CBBLoaiBanDaDat = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jpnBanDangTrong = new javax.swing.JPanel();
        CBBKhuVucBanDangTrong = new javax.swing.JComboBox<>();
        CBBLoaiBanDangTrong = new javax.swing.JComboBox<>();

        jTextField1.setText("jTextField1");

        setPreferredSize(new java.awt.Dimension(852, 582));

        jPanel4.setPreferredSize(new java.awt.Dimension(848, 570));

        jPanel3.setPreferredSize(new java.awt.Dimension(856, 170));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel5.setPreferredSize(new java.awt.Dimension(567, 48));

        btnDatBan.setBackground(new java.awt.Color(0, 102, 102));
        btnDatBan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDatBan.setForeground(new java.awt.Color(255, 255, 255));
        btnDatBan.setText("Đặt bàn");
        btnDatBan.setBorderPainted(false);
        btnDatBan.setOpaque(true);
        btnDatBan.setPreferredSize(new java.awt.Dimension(100, 36));
        btnDatBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatBanActionPerformed(evt);
            }
        });
        jPanel5.add(btnDatBan);

        btnXong.setBackground(new java.awt.Color(0, 153, 51));
        btnXong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXong.setForeground(new java.awt.Color(255, 255, 255));
        btnXong.setText("Xong");
        btnXong.setBorderPainted(false);
        btnXong.setOpaque(true);
        btnXong.setPreferredSize(new java.awt.Dimension(100, 36));
        btnXong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXongActionPerformed(evt);
            }
        });
        jPanel5.add(btnXong);

        btnHuyDat.setBackground(new java.awt.Color(153, 0, 0));
        btnHuyDat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuyDat.setForeground(new java.awt.Color(255, 255, 255));
        btnHuyDat.setText("Huỷ Đặt");
        btnHuyDat.setBorderPainted(false);
        btnHuyDat.setPreferredSize(new java.awt.Dimension(100, 36));
        btnHuyDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyDatActionPerformed(evt);
            }
        });
        jPanel5.add(btnHuyDat);

        jPanel8.setLayout(new java.awt.GridLayout(0, 1));

        btn1.setBorderPainted(false);
        btn1.setFocusPainted(false);
        btn1.setOpaque(true);
        btn1.setPreferredSize(new java.awt.Dimension(72, 50));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        txtNgay.setDateFormatString("dd:MM:yyyy");

        txtTenKhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenKhachActionPerformed(evt);
            }
        });

        jLabel1.setText("Bàn :");

        jLabel2.setText("Tên khách :");

        jLabel3.setText("Số điện thoại :");

        jLabel4.setText("Ngày :");

        jLabel12.setText("Ghi chú :");

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane3.setViewportView(txtGhiChu);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtSoDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                        .addGap(226, 226, 226))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTenKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12))
                            .addComponent(jLabel2))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel9.setPreferredSize(new java.awt.Dimension(455, 389));

        jLabel5.setText("Khu vực : ");

        jLabel6.setText("Loại bàn : ");

        jLabel10.setText("Bàn đang trống ");

        jpnBanDaDat.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jScrollPane2.setViewportView(jpnBanDaDat);

        CBBKhuVucBanDaDat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBBKhuVucBanDaDatItemStateChanged(evt);
            }
        });

        CBBLoaiBanDaDat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBBLoaiBanDaDatItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBBKhuVucBanDaDat, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(CBBLoaiBanDaDat, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(CBBKhuVucBanDaDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBBLoaiBanDaDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel7.setText("Khu vực : ");

        jLabel8.setText("Loại bàn : ");

        jLabel9.setText("Bàn đã đặt");

        jpnBanDangTrong.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jScrollPane1.setViewportView(jpnBanDangTrong);

        CBBKhuVucBanDangTrong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBBKhuVucBanDangTrongItemStateChanged(evt);
            }
        });
        CBBKhuVucBanDangTrong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBBKhuVucBanDangTrongActionPerformed(evt);
            }
        });

        CBBLoaiBanDangTrong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBBLoaiBanDangTrongItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBBKhuVucBanDangTrong, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(CBBLoaiBanDangTrong, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addContainerGap(40, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(CBBLoaiBanDangTrong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CBBKhuVucBanDangTrong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    public void loadCBBLoaiBan() {
        ArrayList<LoaiBan> list = BLLKhac.GetAllLoaiBan();
        BLLOrder.loadComboBoxLoaiBan(CBBLoaiBanDangTrong, list);
        BLLOrder.loadComboBoxLoaiBan(CBBLoaiBanDaDat, list);
        MyComboBox cbbLoaiBan = (MyComboBox) CBBLoaiBanDangTrong.getSelectedItem();
    }

    public void loadCBBKhuVuc() {
        ArrayList<KhuVuc> list = BLLKhac.GetAllKhuVuc();
        BLLOrder.loadComboBoxKhuVuc(CBBKhuVucBanDangTrong, list);
        BLLOrder.loadComboBoxKhuVuc(CBBKhuVucBanDaDat, list);
        MyComboBox cbbKhuVuc = (MyComboBox) CBBKhuVucBanDaDat.getSelectedItem();
        System.out.println(cbbKhuVuc.MaInt());
        loadCBBLoaiaBanOKs = true;
    }

    public void loadGiaoDien() {
        jpnBanDangTrong.removeAll();
        MyComboBox cbbKhuVuc = (MyComboBox) CBBKhuVucBanDangTrong.getSelectedItem();
        if (CBBLoaiBanDangTrong == null) {
            return;
        }
        int maKhuVuc = cbbKhuVuc.MaInt();
        if (!loadCBBLoaiaBanOKs) {
            return;
        }
        MyComboBox cbbLoaiBan = (MyComboBox) CBBLoaiBanDangTrong.getSelectedItem();
        if (cbbLoaiBan == null) {
            return;
        }
        int maLoaiBan = cbbLoaiBan.MaInt();
        ArrayList<Ban> list = BLLBan.timBanTheoMaLoaiVaKhuVuc(maKhuVuc, maLoaiBan);
        new BLLDatBan().loadDaDat(jpnBanDangTrong, btn1, list,txtTenKhach,txtSoDienThoai, txtNgay,txtGhiChu);
//        BLLOrder.loadBan(jpnBanDaDat, new JButton(), new JButton(), maKhuVuc, maLoaiBan);

        SwingUtilities.updateComponentTreeUI(jpnBanDangTrong);
    }
    private void btnDatBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatBanActionPerformed
        // TODO add your handling code here:
        String tenKhach = txtTenKhach.getText();
        System.out.println("tenKhach "+tenKhach);
        String soDienThoai = txtSoDienThoai.getText();
        Date date = txtNgay.getDate();
        String ghiChu = txtGhiChu.getText();
        if (tenKhach.trim().length() <= 0) {
            Caution.ThongBao("Tên không được để trống!");
            return;
        }
        if (soDienThoai.trim().length() <= 0) {
            Caution.ThongBao("Số điện thoại không được để trống!");
            return;
        }
        if (date.getTime() - new Date().getTime() < 0) {
            Caution.ThongBao("Ngày không hợp lệ!");
            return;
        }
        if (ghiChu.trim().length() <= 0) {
            Caution.ThongBao("Ghi chú không được để trống!");
            return;
        }
        String tenBanCu = btn1.getText();
        if (tenBanCu.equals("")) {
            return;
        }

        ArrayList<Ban> arrBanCu = BLLOrder.findTableByName(tenBanCu);
        int maBanCu = arrBanCu.get(0).getMaBan();
        DTO.DatBan ban = new DTO.DatBan();
        ban.setMaBan(maBanCu);
        ban.setMaNhanVien(BLL.BLLNhanVien.GetAccountNhanVien().getMaNhanVien());
        ban.setNgayDat(new Date());
        ban.setNgayChoi(date);
        ban.setSoDienThoai(soDienThoai);
        ban.setTenKhach(tenKhach);
        ban.setGhiChu(ghiChu);
        ban.setTinhTrang("1");
        BLLDatBan.insert(ban);
        
        BLLBan.updateTinhTrangBan(maBanCu, "2");
        txtGhiChu.setText("");
        txtNgay.setDate(null);
        txtSoDienThoai.setText("");
        txtTenKhach.setText("");
        jpnBanDangTrong.removeAll();
        jpnBanDaDat.removeAll();

        MyComboBox cbbKhuVucDaDat = (MyComboBox) CBBKhuVucBanDangTrong.getSelectedItem();
        if (CBBLoaiBanDangTrong == null) {
            return;
        }
        int maKhuVucDaDat = cbbKhuVucDaDat.MaInt();
        if (!loadCBBLoaiaBanOK) {
            return;
        }
        MyComboBox cbbLoaiBanDatDat = (MyComboBox) CBBLoaiBanDangTrong.getSelectedItem();
        if (cbbLoaiBanDatDat == null) {
            return;
        }
        int maLoaiBanDatDat = cbbLoaiBanDatDat.MaInt();
        ArrayList<Ban> listDaDat = BLLBan.timBanTheoMaLoaiVaKhuVuc(maKhuVucDaDat, maLoaiBanDatDat);

        MyComboBox cbbKhuVuc = (MyComboBox) CBBKhuVucBanDaDat.getSelectedItem();
        if (CBBKhuVucBanDaDat == null) {
            return;
        }
        int maKhuVuc = cbbKhuVuc.MaInt();
        if (!loadCBBLoaiaBanOKs) {
            return;
        }
        MyComboBox cbbLoaiBan = (MyComboBox) CBBLoaiBanDaDat.getSelectedItem();
        if (cbbLoaiBan == null) {
            return;
        }
        int maLoaiBan = cbbLoaiBan.MaInt();
        ArrayList<Ban> list = BLLBan.timBanTheoMaLoaiVaKhuVuc(maKhuVuc, maLoaiBan);
        new BLLDatBan().loadDaDat(jpnBanDangTrong, btn1, listDaDat,txtTenKhach,txtSoDienThoai, txtNgay,txtGhiChu);
        new BLLOrder().loadBanDangTrong(jpnBanDaDat, btn1, list);

        SwingUtilities.updateComponentTreeUI(jpnBanDangTrong);
        SwingUtilities.updateComponentTreeUI(jpnBanDaDat);
        btn1.setText("");
        btn1.setBackground(null);

        Caution.ThongBaoCoIcon("Thông báo", "Đặt bàn thành công", 1);
        Order.updateBan = true;
    }//GEN-LAST:event_btnDatBanActionPerformed

    private void btnXongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXongActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed
    static boolean loadCBBLoaiaBanOKs = false;
    private void CBBKhuVucBanDangTrongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBBKhuVucBanDangTrongItemStateChanged
        // TODO add your handling code here:
//        jpnBanDaDat.setPreferredSize(new Dimension(455, 0));
        jpnBanDangTrong.removeAll();
        MyComboBox cbbKhuVuc = (MyComboBox) CBBKhuVucBanDangTrong.getSelectedItem();
        if (CBBLoaiBanDangTrong == null) {
            return;
        }
        int maKhuVuc = cbbKhuVuc.MaInt();
        if (!loadCBBLoaiaBanOKs) {
            return;
        }
        MyComboBox cbbLoaiBan = (MyComboBox) CBBLoaiBanDangTrong.getSelectedItem();
        if (cbbLoaiBan == null) {
            return;
        }
        int maLoaiBan = cbbLoaiBan.MaInt();
        ArrayList<Ban> list = BLLBan.timBanTheoMaLoaiVaKhuVuc(maKhuVuc, maLoaiBan);
       new BLLDatBan().loadDaDat(jpnBanDangTrong, btn1, list,txtTenKhach,txtSoDienThoai, txtNgay,txtGhiChu);
//        BLLOrder.loadBan(jpnBanDaDat, new JButton(), new JButton(), maKhuVuc, maLoaiBan);

        SwingUtilities.updateComponentTreeUI(jpnBanDangTrong);

    }//GEN-LAST:event_CBBKhuVucBanDangTrongItemStateChanged

    private void CBBLoaiBanDangTrongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBBLoaiBanDangTrongItemStateChanged
        // TODO add your handling code here:
        jpnBanDangTrong.removeAll();

        MyComboBox cbbLoaiBan = (MyComboBox) CBBLoaiBanDangTrong.getSelectedItem();
        if (CBBLoaiBanDangTrong == null) {
            return;
        }
        MyComboBox cbbKhuVuc = (MyComboBox) CBBKhuVucBanDangTrong.getSelectedItem();
        int maLoaiBan = cbbLoaiBan.MaInt();
        int maKhuVuc = cbbKhuVuc.MaInt();
        ArrayList<Ban> list = BLLBan.timBanTheoMaLoaiVaKhuVuc(maKhuVuc, maLoaiBan);
        new BLLDatBan().loadDaDat(jpnBanDangTrong, btn1, list,txtTenKhach,txtSoDienThoai, txtNgay,txtGhiChu);
        SwingUtilities.updateComponentTreeUI(jpnBanDangTrong);
    }//GEN-LAST:event_CBBLoaiBanDangTrongItemStateChanged

    private void CBBKhuVucBanDaDatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBBKhuVucBanDaDatItemStateChanged
        // TODO add your handling code here:
        jpnBanDaDat.removeAll();
        MyComboBox cbbKhuVuc = (MyComboBox) CBBKhuVucBanDaDat.getSelectedItem();
        if (CBBKhuVucBanDaDat == null) {
            return;
        }
        int maKhuVuc = cbbKhuVuc.MaInt();
        if (!loadCBBLoaiaBanOKs) {
            return;
        }
        MyComboBox cbbLoaiBan = (MyComboBox) CBBLoaiBanDaDat.getSelectedItem();
        if (cbbLoaiBan == null) {
            return;
        }
        int maLoaiBan = cbbLoaiBan.MaInt();
        ArrayList<Ban> list = BLLBan.timBanTheoMaLoaiVaKhuVuc(maKhuVuc, maLoaiBan);
        new BLLDatBan().loadDaDat(jpnBanDangTrong, btn1, list,txtTenKhach,txtSoDienThoai, txtNgay,txtGhiChu);
        SwingUtilities.updateComponentTreeUI(jpnBanDaDat);
    }//GEN-LAST:event_CBBKhuVucBanDaDatItemStateChanged

    private void CBBLoaiBanDaDatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBBLoaiBanDaDatItemStateChanged
        // TODO add your handling code here:
        jpnBanDaDat.removeAll();

        MyComboBox cbbLoaiBan = (MyComboBox) CBBLoaiBanDaDat.getSelectedItem();
        if (CBBLoaiBanDaDat == null) {
            return;
        }
        MyComboBox cbbKhuVuc = (MyComboBox) CBBKhuVucBanDaDat.getSelectedItem();
        int maLoaiBan = cbbLoaiBan.MaInt();
        int maKhuVuc = cbbKhuVuc.MaInt();
        ArrayList<Ban> list = BLLBan.timBanTheoMaLoaiVaKhuVuc(maKhuVuc, maLoaiBan);
        new BLLOrder().loadBanDangTrong(jpnBanDaDat, btn1, list);
        SwingUtilities.updateComponentTreeUI(jpnBanDaDat);
    }//GEN-LAST:event_CBBLoaiBanDaDatItemStateChanged

    private void btnHuyDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyDatActionPerformed
        // TODO add your handling code here:
        String ten = btn1.getText();
        if (ten.length() < 1) {
            return;
        }
        ArrayList<Ban> arrBanCu = BLLOrder.findTableByName(ten);
        int maBanCu = arrBanCu.get(0).getMaBan();
        System.out.println("tinh trang "+arrBanCu.get(0).getTinhTrang());
        
        if(arrBanCu.get(0).getTinhTrang().equals("0")){
            Caution.ThongBaoDonGian("Thông báo", "Bàn này chưa đặt!");
            return;
        }
        
        boolean xacNhan = Caution.ThongBao("Bạn muốn huỷ đặt " + ten);
        
        if (xacNhan) {
            txtGhiChu.setText("");
            txtNgay.setDate(null);
            txtSoDienThoai.setText("");
            txtTenKhach.setText("");
            
            ArrayList<DTO.DatBan> arrBan = BLLDatBan.layDuLieuTheoBan(maBanCu, "1");
            BLLBan.updateTinhTrangBan(maBanCu, "0");
            
            BLLDatBan.updateTinhTrang(arrBan.get(0).getMaDat(), "2");
            
            jpnBanDangTrong.removeAll();
            jpnBanDaDat.removeAll();

            MyComboBox cbbKhuVucDaDat = (MyComboBox) CBBKhuVucBanDangTrong.getSelectedItem();
            if (CBBLoaiBanDangTrong == null) {
                return;
            }
            int maKhuVucDaDat = cbbKhuVucDaDat.MaInt();
            if (!loadCBBLoaiaBanOK) {
                return;
            }
            MyComboBox cbbLoaiBanDatDat = (MyComboBox) CBBLoaiBanDangTrong.getSelectedItem();
            if (cbbLoaiBanDatDat == null) {
                return;
            }
            int maLoaiBanDatDat = cbbLoaiBanDatDat.MaInt();
            ArrayList<Ban> listDaDat = BLLBan.timBanTheoMaLoaiVaKhuVuc(maKhuVucDaDat, maLoaiBanDatDat);

            MyComboBox cbbKhuVuc = (MyComboBox) CBBKhuVucBanDaDat.getSelectedItem();
            if (CBBKhuVucBanDaDat == null) {
                return;
            }
            int maKhuVuc = cbbKhuVuc.MaInt();
            if (!loadCBBLoaiaBanOKs) {
                return;
            }
            MyComboBox cbbLoaiBan = (MyComboBox) CBBLoaiBanDaDat.getSelectedItem();
            if (cbbLoaiBan == null) {
                return;
            }
            int maLoaiBan = cbbLoaiBan.MaInt();
            ArrayList<Ban> list = BLLBan.timBanTheoMaLoaiVaKhuVuc(maKhuVuc, maLoaiBan);
            new BLLDatBan().loadDaDat(jpnBanDangTrong, btn1, listDaDat,txtTenKhach,txtSoDienThoai, txtNgay,txtGhiChu);
            new BLLOrder().loadBanDangTrong(jpnBanDaDat, btn1, list);

            SwingUtilities.updateComponentTreeUI(jpnBanDangTrong);
            SwingUtilities.updateComponentTreeUI(jpnBanDaDat);
            Order.updateBan = true;
        }
    }//GEN-LAST:event_btnHuyDatActionPerformed

    private void txtTenKhachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenKhachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenKhachActionPerformed

    private void CBBKhuVucBanDangTrongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBBKhuVucBanDangTrongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBBKhuVucBanDangTrongActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBBKhuVucBanDaDat;
    private javax.swing.JComboBox<String> CBBKhuVucBanDangTrong;
    private javax.swing.JComboBox<String> CBBLoaiBanDaDat;
    private javax.swing.JComboBox<String> CBBLoaiBanDangTrong;
    public javax.swing.JButton btn1;
    private javax.swing.JButton btnDatBan;
    private javax.swing.JButton btnHuyDat;
    public javax.swing.JButton btnXong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.components.JSpinField jSpinField1;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JPanel jpnBanDaDat;
    public javax.swing.JPanel jpnBanDangTrong;
    private javax.swing.JTextArea txtGhiChu;
    private com.toedter.calendar.JDateChooser txtNgay;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenKhach;
    // End of variables declaration//GEN-END:variables
}
