/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.DanhMuc;

import BLL.BLLDoDung;
import java.util.ArrayList;
import java.awt.Color;
import DTO.DoDung;
import DTO.LoaiDoDung;
import EXTENDED.MyComboBox;
import GUI.HomeScreen;

/**
 *
 * @author Admin
 */
public class pnlDoDung extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public static int vitri;
    public static int MaDoDung = 0;
    public static boolean StatusDoDung = true;

    public pnlDoDung() {
        initComponents();
        setBackground(Color.white);
        LoadDoDung();
        tbdodung.setDefaultEditor(Object.class, null);
        ArrayList<LoaiDoDung> arrdv = BLL.BLLKhac.GetAllLoaiDoDung();
        BLL.BLLKhac.DoVaoCBLoaiDoDung(arrdv, cbloaidodung);
        jdlThongbaohethang();

    }

    public static void jdlThongbaohethang() {
        jdlThongbaohethang jdl = new jdlThongbaohethang();
        BLLDoDung.thongbaosaphethang(jdl);
    }

    public static void LoadDoDung() {
        ArrayList<DoDung> arr = BLL.BLLDoDung.GetAllDoDung();
        BLL.BLLDoDung.DoVaoTable(arr, tbdodung);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnltextfield = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        cbloaidodung = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        txttimkiem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        pnlkhach = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbdodung = new javax.swing.JTable();

        pnltextfield.setLayout(new java.awt.GridLayout(1, 0));

        cbloaidodung.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loại khách hàng", "Loại đồ dùng", "Khu vực", "Chức vụ", "Đơn vị tính" }));
        cbloaidodung.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbloaidodungItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(cbloaidodung, 0, 296, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(cbloaidodung, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 3, Short.MAX_VALUE)))
        );

        pnltextfield.add(jPanel1);

        txttimkiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txttimkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttimkiemKeyReleased(evt);
            }
        });

        jLabel1.setText("Tìm kiếm");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txttimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        pnltextfield.add(jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        pnltextfield.add(jPanel4);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        pnltextfield.add(jPanel11);

        tbdodung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ));
        tbdodung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbdodungMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbdodung);

        javax.swing.GroupLayout pnlkhachLayout = new javax.swing.GroupLayout(pnlkhach);
        pnlkhach.setLayout(pnlkhachLayout);
        pnlkhachLayout.setHorizontalGroup(
            pnlkhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlkhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1232, Short.MAX_VALUE))
        );
        pnlkhachLayout.setVerticalGroup(
            pnlkhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
            .addGroup(pnlkhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlkhachLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnltextfield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlkhach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnltextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlkhach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbdodungMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdodungMousePressed
        vitri = tbdodung.getSelectedRow();
        MaDoDung = Integer.parseInt(tbdodung.getValueAt(vitri, 1).toString());
        String thu = tbdodung.getValueAt(vitri, 9).toString();
        if (thu.equals("Còn bán")) {
            StatusDoDung = true;
        } else {
            StatusDoDung = false;
        }
        if (vitri >= 0 && evt.getClickCount() > 1) {
            MaDoDung = Integer.parseInt(tbdodung.getValueAt(vitri, 1).toString());
            String thu2 = tbdodung.getValueAt(vitri, 9).toString();
            if (thu2.equals("Còn bán")) {
                StatusDoDung = true;
            } else {
                StatusDoDung = false;
            }
            jdlSuaDoDung jdlsuadd = new jdlSuaDoDung(new HomeScreen(), true);
            jdlsuadd.setVisible(true);
        }
    }//GEN-LAST:event_tbdodungMousePressed

    private void cbloaidodungItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbloaidodungItemStateChanged

        MyComboBox cBBB = (MyComboBox) cbloaidodung.getSelectedItem();
        int LDD = cBBB.MaInt();
        ArrayList<DoDung> arrdv = BLL.BLLDoDung.FindByLoaiDoDung(LDD);
        BLL.BLLDoDung.DoVaoTable(arrdv, tbdodung);

    }//GEN-LAST:event_cbloaidodungItemStateChanged

    private void txttimkiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimkiemKeyReleased
        String TenDD = txttimkiem.getText();
        ArrayList<DoDung> arrdv = BLL.BLLDoDung.FindbyTenDoDung(TenDD);
        BLL.BLLDoDung.DoVaoTable(arrdv, tbdodung);
    }//GEN-LAST:event_txttimkiemKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> cbloaidodung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JPanel pnlkhach;
    private javax.swing.JPanel pnltextfield;
    public static javax.swing.JTable tbdodung;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
}
