/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.DanhMuc;

import DTO.ChucVu;
import DTO.DonViTinh;
import DTO.KhuVuc;
import DTO.KhuyenMai;
import DTO.LoaiBan;
import DTO.LoaiDoDung;
import static GUI.DanhMuc.pnlDanhMuc.a;
import static GUI.DanhMuc.pnlDanhMuc.btndelete;
import static GUI.DanhMuc.pnlDanhMuc.btnthem;
import static GUI.DanhMuc.pnlDanhMuc.btnxuatds;
import static GUI.DanhMuc.pnlDanhMuc.pnlbtncon;
import GUI.HomeScreen;
import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author Admin
 */
public class pnlKhac extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public static int index;
    public static String TenKhacTuCBX = "";
    public static String TenKhacTuTable = "";
    public static String GiatienTuTable = "";
    public static int MaKhuyenMaiTuTable = 0;

    public pnlKhac() {
        initComponents();
        setBackground(Color.white);
        tbchung.setDefaultEditor(Object.class, null);
        TenKhacTuCBX = cbloaidodung.getSelectedItem().toString();
        ArrayList<LoaiDoDung> arr = BLL.BLLKhac.GetAllLoaiDoDung();
        BLL.BLLKhac.DoVaoTableLoaiDoDung(arr, tbchung);
    }

    public static void LoadKhac() {
        if (TenKhacTuCBX.equals("Khuyến mãi")) {
            ArrayList<KhuyenMai> arr = BLL.BLLKhac.GetAllKhuyenMai();
            BLL.BLLKhac.DoVaoTableKhuyenMai(arr, tbchung);
        }
        if (TenKhacTuCBX.equals("Loại đồ dùng")) {
            ArrayList<LoaiDoDung> arr = BLL.BLLKhac.GetAllLoaiDoDung();
            BLL.BLLKhac.DoVaoTableLoaiDoDung(arr, tbchung);
        }
        if (TenKhacTuCBX.equals("Chức vụ")) {
            ArrayList<ChucVu> arr = BLL.BLLKhac.GetAllChucVu();
            BLL.BLLKhac.DoVaoTableChucVu(arr, tbchung);
        }
        if (TenKhacTuCBX.equals("Khu vực")) {
            ArrayList<KhuVuc> arr = BLL.BLLKhac.GetAllKhuVuc();
            BLL.BLLKhac.DoVaoTableKhuVuc(arr, tbchung);
        }
        if (TenKhacTuCBX.equals("Đơn vị tính")) {
            ArrayList<DonViTinh> arr = BLL.BLLKhac.GetAllDVT();
            BLL.BLLKhac.DoVaoTableDVT(arr, tbchung);
        }
        if (TenKhacTuCBX.equals("Loại bàn")) {
            ArrayList<LoaiBan> arr = BLL.BLLKhac.GetAllLoaiBan();
            BLL.BLLKhac.DoVaoTableLoaiBan(arr, tbchung);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnltextfield = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        cbloaidodung = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        pnlkhach = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbchung = new javax.swing.JTable();

        pnltextfield.setLayout(new java.awt.GridLayout(1, 0));

        cbloaidodung.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loại đồ dùng", "Khu vực", "Chức vụ", "Đơn vị tính", "Loại bàn", "Khuyến mãi" }));
        cbloaidodung.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbloaidodungItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(cbloaidodung, 0, 296, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(cbloaidodung, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 3, Short.MAX_VALUE)))
        );

        pnltextfield.add(jPanel1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        pnltextfield.add(jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        pnltextfield.add(jPanel4);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        pnltextfield.add(jPanel11);

        tbchung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tbchung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbchungMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbchung);

        javax.swing.GroupLayout pnlkhachLayout = new javax.swing.GroupLayout(pnlkhach);
        pnlkhach.setLayout(pnlkhachLayout);
        pnlkhachLayout.setHorizontalGroup(
            pnlkhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlkhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1232, Short.MAX_VALUE))
        );
        pnlkhachLayout.setVerticalGroup(
            pnlkhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
            .addGroup(pnlkhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlkhachLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnltextfield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlkhach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnltextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlkhach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbloaidodungItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbloaidodungItemStateChanged
        TenKhacTuCBX = cbloaidodung.getSelectedItem().toString();
        LoadKhac();
        TenKhacTuTable = "";
        if (cbloaidodung.getSelectedItem().toString().equals("Loại bàn")) {
            jdlthemloaiban jdl = new jdlthemloaiban(new HomeScreen(), true);
            pnlbtncon(a, jdl, btnthem, btnxuatds, btndelete);
        } else if (cbloaidodung.getSelectedItem().toString().equals("Khuyến mãi")) {
            jdlThemKhuyenMai km = new jdlThemKhuyenMai(new HomeScreen(), true);
            pnlbtncon(a, km, btnthem, btnxuatds, btndelete);
        } else {
            jdlthemkhac khac = new jdlthemkhac(new HomeScreen(), true);
            pnlbtncon(a, khac, btnthem, btnxuatds, btndelete);
        }


    }//GEN-LAST:event_cbloaidodungItemStateChanged

    private void tbchungMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbchungMousePressed
        index = tbchung.getSelectedRow();
        TenKhacTuTable = tbchung.getValueAt(index, 1).toString();
        if (index >= 0 && evt.getClickCount() > 1) {
            TenKhacTuTable = tbchung.getValueAt(index, 1).toString();
            if (cbloaidodung.getSelectedItem().toString().equals("Loại bàn")) {
                GiatienTuTable = tbchung.getValueAt(index, 2).toString();
                jdlsualoaiban jdlslb = new jdlsualoaiban(new HomeScreen(), true);
                jdlslb.setVisible(true);
            } else if (cbloaidodung.getSelectedItem().toString().equals("Khuyến mãi")) {
                MaKhuyenMaiTuTable = Integer.parseInt(tbchung.getValueAt(index, 1).toString());
                jdlSuaKhuyenMai jdlslb = new jdlSuaKhuyenMai(new HomeScreen(), true);
                jdlslb.setVisible(true);
            } else {
                jdlSuaKhac jdlsuadd = new jdlSuaKhac(new HomeScreen(), true);
                jdlsuadd.setVisible(true);

            }
        }
    }//GEN-LAST:event_tbchungMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbloaidodung;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JPanel pnlkhach;
    private javax.swing.JPanel pnltextfield;
    public static javax.swing.JTable tbchung;
    // End of variables declaration//GEN-END:variables
}
